config/routes.rb
Rails.application.routes.draw do
  # get 'agencies/index'
  # get 'agencies/new'
  # get 'agencies/create'
  # get 'agencies/show'
  # get 'agencies/edit'
  # get 'agencies/update'
  # get 'agencies/destroy'
  resources :agencies
  root :to => 'agencies#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/agency.rb
class Agency < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :billing_terms, presence: true
  validates :credit_rating, presence: true
  validates :billing_terms, :numericality => {:only_integer => true}
  enum credit_rating: %i[Good Fair Poor]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/agencies_controller.rb
require 'pry'

class AgenciesController < ApplicationController
  def index
    @agencies = Agency.all
  end

  def new
    @agency = Agency.new
  end

  def create
    @agency = Agency.create(params.require(:agency).permit(:name, :billing_terms, :credit_rating))
    if @agency.valid?
      redirect_to agencies_path
    else
      render :new
  end

  def edit
    @agency = Agency.find(params[:id])
  end

  def update
    @agency = Agency.find(params[:id])
    if @agency.update_attributes(params.require(:agency).permit(:name, :billing_terms, :credit_rating))
      flash[:success] = "Agency Updated"
      redirect_to agencies_path
    else
      render action: :edit
  end

  def show
    @agency = Agency.find(params[:id])
  end

  def destroy
    @agency = Agency.find(params[:id])
    @agency.destroy
    redirect_to agency_path
  end
end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agencies/create.html.erb
<h1>Agencies#create</h1>
<p>Find me in app/views/agencies/create.html.erb</p>

app/views/agencies/destroy.html.erb
<h1>Agencies#destroy</h1>
<p>Find me in app/views/agencies/destroy.html.erb</p>

app/views/agencies/edit.html.erb
<style>
input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: rgb(32,150,243);
  color: white;
  padding: 14px 2px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  font-size: 15px;
  cursor: pointer;
}
</style>

<%= form_for @agency do |f|%>
  <body>
  <div class="div">
  <%= f.label :name%><br>
  <%= f.text_field :name%><br>
  <%= f.label :billing_terms%><br>
  <%= f.text_field :billing_terms, {min: 1, max: 2}%><br>
  <%= f.label :credit_rating%><br>
  <%= f.select :credit_rating, Agency.credit_ratings.keys, {}, class: 'user-roles-select' %><br><br>
  <div class="grid-container">
    <div class="submit-container">
      <%= f.submit%>
    </div>
    <div class="cancel-container">
  <%= link_to "Cancel", agencies_path, {:class=>"cancel-button"} %>
  </div>
  </div>
  <% if @agency.errors.any?%>
  <ul>
    <% @agency.errors.full_messages.each do |message| %>
    <div class="alert alert-warning">
      <strong>Error!</strong> <%= message%>
    </div>
    <% end %>
  </ul>
  <% end %>
</body>

  <%end%>

  <!DOCTYPE html>
  <html>
  </html>

app/views/agencies/index.html.erb
<%= button_to "Add New Agency", new_agency_path, :class => 'add-agency' ,method: :get%>

  <html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>
<nav>
<div class="flex-container">
<table>
  <tr>
    <th>Agency Name</th>
    <th>Billing Terms</th>
    <th>Credit Status</th>
    <th>Actions</th>
  </tr>
  <% @agencies.each do |agency|%>
  <tr>
      <td><%= agency.name%></td>
      <td><%= agency.billing_terms%></td>
      <td><%= agency.credit_rating%></td>
      <td><%= button_to "Edit", edit_agency_path(agency), method: :get , :class => 'button'%></td>

    <%end%>
  </tr>
</table>
</div>
</nav>
</body>
</html>

app/views/agencies/new.html.erb
<style>
input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: rgb(32,150,243);
  color: white;
  padding: 14px 2px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  font-size: 15px;
  cursor: pointer;
}
</style>

<%= form_for @agency do |f|%>
  <body>
  <div class="div">
  <%= f.label :name%><br>
  <%= f.text_field :name%><br>
  <%= f.label :billing_terms%><br>
  <%= f.text_field :billing_terms, {min: 1, max: 2}%><br>
  <%= f.label :credit_rating%><br>
  <%= f.select :credit_rating, Agency.credit_ratings.keys, {}, class: 'user-roles-select' %><br><br>
  <div class="grid-container">
    <div class="submit-container">
      <%= f.submit%>
    </div>
    <div class="cancel-container">
  <%= link_to "Cancel", agencies_path, {:class=>"cancel-button"} %>
  </div>
  </div>
  <% if @agency.errors.any?%>
  <ul>
    <% @agency.errors.full_messages.each do |message| %>
    <div class="alert alert-warning">
      <strong>Error!</strong> <%= message%>
    </div>
    <% end %>
  </ul>
  <% end %>
</body>

  <%end%>

  <!DOCTYPE html>
  <html>
  </html>

app/views/agencies/show.html.erb
<h1>Agencies#show</h1>
<p>Find me in app/views/agencies/show.html.erb</p>

app/views/agencies/update.html.erb
<h1>Agencies#update</h1>
<p>Find me in app/views/agencies/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mars</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>